// Generated by @wisent-ai/landing-cli@0.1.0. Shapes mirror @wisent-ai/landing-cli's plan schema.

export type Action = {
  label: string;
  kind: "url" | "dialog" | "form";
  target: string;
};

export type SiteContent = {
  product: string;
  siteName: string;
  domain: string;
  description: string;
  audience: string;
  sourceUrl: string;
  docsUrl: string | null;
  discordUrl: string | null;
  ogImageAlt: string;
  commitment: string | null;
  primaryAction: Action;
  secondaryAction: { label: string; purpose?: string; target?: string } | null;
  nav: { label: string; href: string }[];
  footer: { label: string; href: string }[];
};

export type Artifact =
  | { type: "terminal"; caption: string; lines: string[] }
  | { type: "code"; caption: string; language: string; code: string }
  | { type: "table"; caption: string; columns: string[]; rows: string[][] };

export type Section =
  | {
      kind: "recognition";
      id: string;
      heading: string;
      lede: string;
      items: { title: string; text: string }[];
    }
  | {
      kind: "mechanism";
      id: string;
      heading: string;
      lede: string;
      items: { step: string; title: string; text: string }[];
    }
  | {
      kind: "proof";
      id: string;
      heading: string;
      lede: string;
      artifact: Artifact;
    }
  | {
      kind: "objection";
      id: string;
      heading: string;
      items: { question: string; answer: string }[];
    }
  | { kind: "decision"; id: string; heading: string; lede: string };

export type Plan = {
  schemaVersion: 1;
  hero: {
    eyebrow: string;
    headline: string;
    lede: string;
    metaDescription: string;
    proofStrip: string[];
  };
  sections: Section[];
};
